version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    allow:
      - dependency-type: "all"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
